# Generated by Django 4.0 on 2021-12-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creator',
            new_name='maker',
        ),
    ]
