# Generated by Django 4.0 on 2021-12-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_creator_note_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='maker',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='note',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
