# Generated by Django 4.0 on 2021-12-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='modified_date',
        ),
    ]
